<a href="https://colab.research.google.com/github/W-teddy/First-/blob/main/Time_Series_Forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imported dependencies

In [15]:
pip install prophet

Requirement already satisfied: prophet in /usr/local/lib/python3.10/dist-packages (1.1.4)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from prophet) (1.1.0)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.10/dist-packages (from prophet) (1.22.4)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from prophet) (3.7.1)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from prophet) (1.5.3)
Requirement already satisfied: LunarCalendar>=0.0.9 in /usr/local/lib/python3.10/dist-packages (from prophet) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from prophet) (2.4.0)
Requirement already satisfied: holidays>=0.25 in /usr/local/lib/python3.10/dist-packages (from prophet) (0.29)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.10/dist-packages (from prophet) (2.8.2)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.10/dist-packages (from prophet) (4.65.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from prophet) (6.0.0)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.10/dist-packages (from convertdate>=2.1.2->prophet) (0.5.12)
Requirement already satisfied: ephem>=3.7.5.3 in /usr/local/lib/python3.10/dist-packages (from LunarCalendar>=0.0.9->prophet) (4.1.4)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from LunarCalendar>=0.0.9->prophet) (2022.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (3.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.0->prophet) (1.16.0)

In [1]:
import prophet
import pandas as pd

import warnings;
warnings.simplefilter('ignore')

In [16]:
from prophet import Prophet

Imported data

In [5]:
df=pd.read_csv("dataset.csv")

Preprocessing

In [ ]:
df.head()

In [ ]:
df.describe()

In [6]:
print(df['Product'].unique())
print(df['Store'].unique())

[2667437]
['QLD_CW_ST0203']

In [8]:
df['Year'] = df['Time Date'].apply(lambda x: str(x)[-4:])
df['Month'] = df['Time Date'].apply(lambda x: str(x)[-6:-4])
df['Day'] = df['Time Date'].apply(lambda x: str(x)[:-6])
df['ds'] = pd.DatetimeIndex(df['Year']+'-'+df['Month']+'-'+df['Day'])

In [9]:
df = df.loc[(df['Product']==2667437) & (df['Store']=='QLD_CW_ST0203')]
df.drop(['Time Date', 'Product', 'Store', 'Year', 'Month', 'Day'], axis=1, inplace=True)
df.columns = ['y', 'ds']

In [ ]:
df.head()

In [17]:
m = Prophet(interval_width=0.95, daily_seasonality=True)
model = m.fit(df)

DEBUG:cmdstanpy:input tempfile: /tmp/tmp9an9wbd5/ulx_65nd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp9an9wbd5/8k8x8bb1.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.10/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=75868', 'data', 'file=/tmp/tmp9an9wbd5/ulx_65nd.json', 'init=/tmp/tmp9an9wbd5/8k8x8bb1.json', 'output', 'file=/tmp/tmp9an9wbd5/prophet_modelplc9f1vq/prophet_model-20230804100503.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
10:05:03 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
10:05:03 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

In [22]:
future = m.make_future_dataframe(periods=4)

In [ ]:
t=m.predict(future)

In [23]:
t.describe()

,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,daily,daily_lower,...,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
count,1084.000000,1084.000000,1084.000000,1084.000000,1084.000000,1084.000000,1084.000000,1084.000000,1084.000000,1084.000000,...,1084.000000,1084.000000,1084.000000,1084.000000,1084.000000,1084.000000,1084.0,1084.0,1084.0,1084.000000
mean,3560.633858,2454.655177,5639.044596,3560.633842,3560.633871,484.791720,484.791720,484.791720,471.949669,471.949669,...,0.012953,0.012953,0.012953,12.829099,12.829099,12.829099,0.0,0.0,0.0,4045.425579
std,325.965818,1188.826376,1186.771859,325.965788,325.965839,1122.903440,1122.903440,1122.903440,0.000000,0.000000,...,20.562628,20.562628,20.562628,1122.725841,1122.725841,1122.725841,0.0,0.0,0.0,1185.117775
min,3042.561512,494.411975,3653.695721,3042.561512,3042.561512,-1199.343457,-1199.343457,-1199.343457,471.949669,471.949669,...,-34.572281,-34.572281,-34.572281,-1637.889468,-1637.889468,-1637.889468,0.0,0.0,0.0,2131.390043
25%,3264.157357,1349.524677,4541.927044,3264.157357,3264.157357,-548.715563,-548.715563,-548.715563,471.949669,471.949669,...,-14.040831,-14.040831,-14.040831,-1020.161569,-1020.161569,-1020.161569,0.0,0.0,0.0,2944.495666
50%,3553.725295,2154.678158,5365.607040,3553.725295,3553.725295,43.058006,43.058006,43.058006,471.949669,471.949669,...,-4.408750,-4.408750,-4.408750,-422.368586,-422.368586,-422.368586,0.0,0.0,0.0,3782.811398
75%,3844.656953,3609.668351,6783.715404,3844.656953,3844.656953,1674.712544,1674.712544,1674.712544,471.949669,471.949669,...,22.490694,22.490694,22.490694,1205.420769,1205.420769,1205.420769,0.0,0.0,0.0,5194.272603
max,4135.010016,4446.199678,7634.955029,4134.997984,4135.019778,1993.297333,1993.297333,1993.297333,471.949669,471.949669,...,25.185178,25.185178,25.185178,1496.162486,1496.162486,1496.162486,0.0,0.0,0.0,5943.437542

In [21]:
future.describe()

                         ds
count                  1084
unique                 1084
top     2018-01-01 00:00:00
freq                      1
first   2018-01-01 00:00:00
last    2020-12-20 00:00:00

In [24]:
t.head()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,daily,...,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2018-01-01,3042.561512,849.094720,3951.286115,3042.561512,3042.561512,-638.399466,-638.399466,-638.399466,471.949669,...,16.625235,16.625235,16.625235,-1126.974369,-1126.974369,-1126.974369,0.0,0.0,0.0,2404.162046
1,2018-01-02,3043.293094,832.401436,3908.147516,3043.293094,3043.293094,-648.583698,-648.583698,-648.583698,471.949669,...,-11.279246,-11.279246,-11.279246,-1109.254121,-1109.254121,-1109.254121,0.0,0.0,0.0,2394.709396
2,2018-01-03,3044.024676,738.794188,3986.452509,3044.024676,3044.024676,-622.804684,-622.804684,-622.804684,471.949669,...,-4.408750,-4.408750,-4.408750,-1090.345602,-1090.345602,-1090.345602,0.0,0.0,0.0,2421.219992
3,2018-01-04,3044.756258,794.561160,4094.880581,3044.756258,3044.756258,-575.884282,-575.884282,-575.884282,471.949669,...,22.490694,22.490694,22.490694,-1070.324645,-1070.324645,-1070.324645,0.0,0.0,0.0,2468.871975
4,2018-01-05,3045.487839,936.042384,4007.502777,3045.487839,3045.487839,-611.942497,-611.942497,-611.942497,471.949669,...,-34.572281,-34.572281,-34.572281,-1049.319885,-1049.319885,-1049.319885,0.0,0.0,0.0,2433.545342